# ------------------------------------------------------------------------------
# File: 02_run_analysis_pipeline.R
# Purpose: Execute the comparison-aware analysis pipeline
# Role: Top-level analysis runner
# Pipeline: Analysis
# Project: Cancer Complexity Analysis
# Author: Ali M. Al-Timimi
# Created: 2026
# ------------------------------------------------------------------------------
NULL

#' Run Analysis Pipeline for Global Cancer Microarray Data
#'
#' @description
#' Executes the full analysis pipeline for the global cancer dataset,
#' including comparison-aware probe selection, pairwise complexity and
#' entropy computation, aggregation, and reporting.
#'
#' This pipeline operates on preprocessed ExpressionSet-derived matrices
#' and predefined normal/tumor comparison maps generated by the
#' preprocessing pipeline.
#'
#' @details
#' The analysis pipeline consists of the following stages:
#' \itemize{
#'   \item Loading expression matrices and comparison maps
#'   \item Comparison-aware probe selection (limma or variability-based)
#'   \item Pairwise complexity and entropy computation
#'   \item Aggregation and summarization of results
#'   \item Optional latent-space notebook execution
#' }
#'
#' Variability-based probe selection supports two modes:
#' \itemize{
#'   \item Fixed-count selection (`top_n`)
#'   \item Threshold-based selection (`var_threshold`)
#' }
#' The selection mode is determined upstream in the pipeline configuration.
#'
#' @note
#' The latent-space workflow operates on a global feature-selection regime
#' defined during preprocessing (e.g., `ml_top_n`) and may therefore use a
#' different feature space than the comparison-specific probe sets used in
#' this pipeline.
#'
#' @seealso
#' \code{\link{run_grouped_probe_filtering}}
#' \code{\link{select_high_variance_probes}}
run_analysis_pipeline <- function() {
  # ---- Stage 1: Configuration + Logging ----
  source(here::here("R/config/global_cancer/analysis_config.R"), local = FALSE)
  
  source(here::here("R/helpers/pipeline_logger.R"))
  logger <- start_log(analysis_pipeline_logfile)
  logger$log("🚀 Starting Global Cancer analysis pipeline...")
  
  # ---- Stage 2: Build matrix + comparison maps ----
  source(here::here("R/helpers/load_annotations.R"))
  load_annotations_if_needed(logger = logger)

  if (isTRUE(build_matrix_maps)) {
    logger$log("⚙️ Building expression matrices and comparison maps...")
    
    # Use existing eset_list if available, otherwise load from disk
    if (exists("eset_list", inherits = TRUE)) {
      logger$log("⏭️ Using existing 'eset_list' from memory.")
    } else {
      if (!file.exists(eset_path))
        stop(glue::glue("❌ Missing ExpressionSets: {eset_path}"))
      
      loaded_objs <- load(eset_path)
      if (!"eset_list" %in% loaded_objs)
        stop("❌ 'eset_list' not found in loaded RData file.")
      
      eset_list <- get("eset_list")
      logger$log("✅ ExpressionSets loaded from disk.")
    }
    
    source(here::here("R/helpers/matrix_builders.R"), local = TRUE)
    
    matrices_hu35ksuba <- build_matrix_lists_by_tissue(eset_list$hu35ksuba)
    matrices_hu6800    <- build_matrix_lists_by_tissue(eset_list$hu6800)
    
    comparison_map_hu35ksuba <- define_predefined_comparisons(names(matrices_hu35ksuba))
    comparison_map_hu6800    <- define_predefined_comparisons(names(matrices_hu6800))
    
    save(
      matrices_hu35ksuba,
      matrices_hu6800,
      comparison_map_hu35ksuba,
      comparison_map_hu6800,
      file = matrices_path
    )
    
    logger$log("💾 Matrix and comparison maps saved.")
  }
  
  # ---- Stage 3: Run comparison-aware probe selection ----
  if (isTRUE(run_filtering)) {
    logger$log("🔀 Checking for expression matrices and comparison maps...")
    source(here::here("R/helpers/load_results_into_global.R"))
    load_matrix_maps(matrices_path, overwrite = TRUE)
    
    logger$log("🧬 Running comparison-aware probe selection...")
    
    source(here::here("R/wrappers/run_grouped_probe_filtering.R"))
    source(here::here("R/filters/select_high_variance_probes.R"))
    
    # ---- Validate variance selection mode ----
    if (!variance_selection_mode %in% c("top_n", "threshold")) {
      logger$log(
        sprintf(
          "⚠️ Invalid variance_selection_mode ('%s'); defaulting to 'threshold'.",
          variance_selection_mode
        ),
        section = "WARNING"
      )
      variance_selection_mode <- "threshold"
    }
    
    # ---- Derive top_n argument for variance filtering ----
    variance_top_n <- if (
      identical(filter_method, "variance") &&
      identical(variance_selection_mode, "top_n")
    ) {
      analysis_top_n
    } else {
      NULL
    }

    res_hu35ksuba <<- run_grouped_probe_filtering(
      matrix_list = matrices_hu35ksuba,
      comparison_map = comparison_map_hu35ksuba,
      chip_id = "hu35ksuba",
      method = filter_method,
      logfc_cutoff = logfc_cutoff,
      pval_cutoff = pval_cutoff,
      var_threshold = var_threshold,
      top_n = variance_top_n,
      variance_selection_mode = variance_selection_mode,
      save_path = here::here(filtered_probes_dir, "filtered_probes_hu35ksuba.rds")
    )
    
    res_hu6800 <<- run_grouped_probe_filtering(
      matrix_list = matrices_hu6800,
      comparison_map = comparison_map_hu6800,
      chip_id = "hu6800",
      method = filter_method,
      logfc_cutoff = logfc_cutoff,
      pval_cutoff = pval_cutoff,
      var_threshold = var_threshold,
      top_n = variance_top_n,
      variance_selection_mode = variance_selection_mode,
      save_path = here::here(filtered_probes_dir, "filtered_probes_hu6800.rds")
    )
    
    logger$log("✅ Completed probe selection.")
  }
  
  # ---- Stage 4: Pairwise comparisons ----
  source(here::here("R/helpers/load_annotations.R"))
  
  if (isTRUE(run_pairwise)) {
    source(here::here("R/helpers/load_results_into_global.R"))
    
    logger$log("🔀 Checking for comparison maps...", section = "PAIRWISE")
    load_matrix_maps(matrices_path, overwrite = TRUE)
    
    logger$log("🔀 Checking for filtered probes...", section = "PAIRWISE")
    load_filtered_results(filtered_probes_dir, overwrite = TRUE)
    
    load_annotations_if_needed(logger = logger)
    
    logger$log("🔀 Starting pairwise comparisons...", section = "PAIRWISE")
    source(here::here("R/wrappers/run_all_pairwise_comparisons.R"))
    
    for (mode in gene_set_modes) {
      logger$log(
        sprintf("🔀 Running pairwise comparisons for gene_set_mode = %s", mode),
        section = "PAIRWISE"
      )
      
      run_all_pairwise_comparisons(
        chips = chips,
        annotations = annotations,
        engines = engines,
        gene_set_mode = mode,
        quantile_cutoff = quantile_cutoff,
        min_probes = min_probes
      )
    }
  }
  
  # ---- Stage 5: Aggregation + gene set annotation ----
  if (isTRUE(run_aggregator)) {
    logger$log("🔀 Checking for pairwise comparison results...")
    source(here::here("R/helpers/load_results_into_global.R"))
    load_comparison_results(data_dir, overwrite = TRUE)
    
    logger$log("📦 Ensuring annotations are loaded...")
    source(here::here("R/helpers/load_annotations.R"))
    load_annotations_if_needed(logger = logger)
    
    logger$log("🔀 Starting results aggregation...")
    source(here::here("R/aggregate/aggregate_engine_results_by_engine.R"))
    source(here::here("R/helpers/gene_set_tools.R"))
    source(here::here("R/helpers/clean_aggregated_results.R"))
    
    agg_complexity <<- aggregate_engine_results_by_engine("complexity")
    agg_entropy    <<- aggregate_engine_results_by_engine("entropy")
    
    agg_complexity <<- attach_gene_set_names(agg_complexity, annotations)
    agg_entropy    <<- attach_gene_set_names(agg_entropy, annotations)
    
    complexity_df <<- clean_aggregated_results(agg_complexity)
    entropy_df    <<- clean_aggregated_results(agg_entropy)
    
    readr::write_csv(complexity_df,
                     file.path(aggregate_dir, "complexity_aggregated_results.csv"))
    readr::write_csv(entropy_df,
                     file.path(aggregate_dir, "entropy_aggregated_results.csv"))
    
    saveRDS(complexity_df,
            file.path(aggregate_dir, "complexity_aggregated_results.rds"))
    saveRDS(entropy_df,
            file.path(aggregate_dir, "entropy_aggregated_results.rds"))
    
    logger$log("✅ Aggregated complexity/entropy results saved.")
  }
  
  # ---- Stage 6: Summarize comparison-level patterns ----
  if (isTRUE(run_comparison_summary)) {
    logger$log("🔀 Checking for cleaned pairwise comparison results...")
    source(here::here("R/helpers/load_results_into_global.R"))
    load_cleaned_results(aggregate_dir, overwrite = TRUE)
    
    logger$log("📊 Summarizing entropy + complexity across comparisons...")
    
    source("R/summarize/summarize_complexity.R")
    source("R/summarize/summarize_entropy.R")
    source("R/summarize/combine_entropy_complexity_summaries.R")
    
    summary_complexity_df <<- recalculate_complexity_summary(complexity_df)
    summary_entropy_df    <<- recalculate_entropy_summary(entropy_df)
    
    summaries_combined_df <<- combine_entropy_complexity_summaries(
      summary_complexity_df, summary_entropy_df
    )
    
    saveRDS(summaries_combined_df,
            file.path(summaries_dir, "summaries_combined_df.rds"))
    readr::write_csv(summaries_combined_df,
                     file.path(summaries_dir, "summaries_combined_df.csv"))
    
    logger$log("✅ Comparison-level summary table saved.")
  }
  
  # ---- Stage 7: Execute latent-space notebooks ----
  if (isTRUE(run_latent_notebooks)) {
    logger$log("🐍 Executing latent-space Jupyter notebooks...", section = "NOTEBOOKS")

    run_notebook <- function(notebook_name) {
      notebook_path <- file.path(latent_notebook_dir, notebook_name)

      if (!file.exists(notebook_path)) {
        logger$log(sprintf("Notebook not found: %s", notebook_path), section = "ERROR")
        stop(sprintf("Notebook not found: %s", notebook_path), call. = FALSE)
      }

      if (isTRUE(execute_notebooks_inplace)) {
        output_args <- c("--inplace")
        output_label <- notebook_path
      } else {
        output_path <- file.path(notebook_executed_dir, notebook_name)
        output_args <- c("--output", shQuote(output_path))
        output_label <- output_path
      }

      args <- c(
        jupyter_prefix_args,
        "nbconvert",
        "--to", "notebook",
        "--execute",
        sprintf("--ExecutePreprocessor.timeout=%s", notebook_timeout_seconds),
        output_args,
        shQuote(notebook_path)
      )
      
      exit_status <- system2(
        command = jupyter_command,
        args = args,
        stdout = TRUE,
        stderr = TRUE
      )
      
      logger$timed(sprintf("Notebook %s", notebook_name), {
        logger$log(sprintf("Launching notebook: %s", notebook_path), section = "NOTEBOOKS")

        old_wd <- getwd()
        on.exit(setwd(old_wd), add = TRUE)
        setwd(latent_notebook_dir)

        notebook_output <- tryCatch(
          system2(command = jupyter_command, args = args, stdout = TRUE, stderr = TRUE),
          warning = function(w) structure(conditionMessage(w), status = 1L),
          error = function(e) structure(conditionMessage(e), status = 1L)
        )

        if (length(notebook_output) > 0) {
          for (line in notebook_output) logger$log(as.character(line), section = "JUPYTER")
        }

        exit_status <- attr(notebook_output, "status")
        if (is.null(exit_status)) exit_status <- 0L

        if (!identical(as.integer(exit_status), 0L)) {
          logger$log(sprintf("Notebook failed with exit status %s: %s", exit_status, notebook_name), section = "ERROR")
          stop(sprintf("Notebook failed: %s", notebook_name), call. = FALSE)
        }

        logger$log(sprintf("Completed notebook successfully: %s", output_label), section = "NOTEBOOKS")
      })

      invisible(TRUE)
    }

    for (notebook_name in latent_notebooks) run_notebook(notebook_name)

    logger$log("✅ Latent-space notebooks completed successfully.", section = "NOTEBOOKS")
  } else {
    logger$log("⏭️ Latent-space notebook execution skipped.", section = "NOTEBOOKS")
  }

  # ---- Stage 8: Latent-space postprocessing ----
  if (isTRUE(run_latent_postprocessing)) {
    logger$timed("Latent-space postprocessing", {
      logger$log("🧾 Running latent-space postprocessing...", section = "LATENT_POST")
      
      source(here::here("R", "latent-space", "build_latent_postprocessing_outputs.R"), local = TRUE)
      
      run_latent_postprocessing(
        logger = logger,
        latent_project_dir = latent_project_dir,
        reports_dir = reports_dir,
        table_dir = latent_postprocessing_table_dir,
        plot_dir = latent_postprocessing_plot_dir,
        chip_id = latent_postprocessing_chip_id,
        mode = latent_postprocessing_mode,
        gene_set_name = latent_postprocessing_gene_set_name
      )
      
      logger$log("✅ Latent-space postprocessing completed successfully.", section = "LATENT_POST")
    })
  } else {
    logger$log("⏭️ Latent-space postprocessing skipped.", section = "LATENT_POST")
  }

  # ---- Final message ----
  logger$log("🎉 Analysis pipeline completed successfully.", section = "PIPELINE")
}

if (sys.nframe() == 0) {
  run_analysis_pipeline()
}
